Repository MySpace-it/MySpace, pull requests merged in 2022-04, with the labels that each got.

#19 fixes #13 adding the dependencies for using realtime database of firebase
  .env
  .gitignore
  composer.json
  composer.lock
  config/database.php
  src/Controller/Controller.php
Labels: database

#27 25 create the home view
  composer.json
  composer.lock
  src/View/home.php
  src/View/modify_profile.php
Labels: frontend

#28 Route
  app/Routing/Router.php
  composer.lock
  public/index.php
Labels: bug
